name: "ECOFLOW SHP Energy Usage"
description: "Get Smart Home Panel energy data from the ECOFLOW API"
version: "0.0.6"
slug: "ecoflow_shp"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
url: "https://github.com/lwsrbrts/hassio-addons/tree/main/ecoflow_shp"
homeassistant_api: true
options:
  energysensor: "sensor.shp_energy_usage"
  epssensor: "binary_sensor.shp_eps_status"
  charginglimitsensor: "number.shp_charging_limit"
  discharginglimitsensor: "number.shp_discharging_limit"
  logging: true
schema:
  efhost: str
  accesskey: str
  secretkey: password
  shpserial: str
  energysensor: str
  epssensor: str
  charginglimitsensor: str
  discharginglimitsensor: str
  polling: int?
  language: str?
  logging: bool