# This builds quicker during dev work.

FROM mcr.microsoft.com/powershell:latest

LABEL \
  io.hass.version="0.0.5" \
  io.hass.type="addon" \
  io.hass.arch="amd64"

ENV TZ=Europe/London

RUN \
  apt-get update \
  && apt-get install locales tzdata -y
#  && locale-gen en_GB.UTF-8 \
#  && update-locale LANG=en_GB.UTF-8

# Set environment variables for locale
#ENV LANG=en_GB.UTF-8 \
#    LANGUAGE=en_GB:en \
#    LC_ALL=en_GB.UTF-8

#RUN \
#  apt-get update \
#  && apt-get upgrade -y \
#  && apt-get clean \
#  && rm -rf /var/lib/apt/lists/*

RUN \
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
  && echo $TZ > /etc/timezone

COPY Run-ScriptsAsThreads.ps1 /app/
COPY Read-HassIoStdIn.ps1 /app/

ENTRYPOINT ["pwsh","-NoProfile", "-NoLogo", "-NonInteractive","-File","/app/Run-ScriptsAsThreads.ps1"]
